import { User, Brand, Platform, Campaign, Shift, Report, DashboardUpdate, SwapRequest } from '@/lib/types/database.types'
import { addDays, subDays, format } from 'date-fns'

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    email: 'admin@livestream.com',
    full_name: 'Admin User',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
    phone: '+1234567890',
    role: 'admin',
    system_permission: 'admin',
    operational_roles: [],
    department: 'Management',
    status: 'active',
    join_date: '2024-01-01',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    email: 'leader@livestream.com',
    full_name: 'Team Leader',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=leader',
    phone: '+1234567891',
    role: 'leader',
    system_permission: 'leader',
    operational_roles: ['host', 'support', 'technical'],
    department: 'Operations',
    status: 'active',
    join_date: '2024-02-01',
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2024-02-01T00:00:00Z',
  },
  {
    id: '3',
    email: 'host1@livestream.com',
    full_name: 'Sarah Johnson',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    phone: '+1234567892',
    role: 'staff',
    system_permission: 'member',
    operational_roles: ['host'],
    department: 'Live Host',
    status: 'active',
    join_date: '2024-03-01',
    created_at: '2024-03-01T00:00:00Z',
    updated_at: '2024-03-01T00:00:00Z',
  },
  {
    id: '4',
    email: 'host2@livestream.com',
    full_name: 'Michael Chen',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=michael',
    phone: '+1234567893',
    role: 'staff',
    system_permission: 'member',
    operational_roles: ['host'],
    department: 'Live Host',
    status: 'active',
    join_date: '2024-03-15',
    created_at: '2024-03-15T00:00:00Z',
    updated_at: '2024-03-15T00:00:00Z',
  },
  {
    id: '5',
    email: 'support1@livestream.com',
    full_name: 'Emily Davis',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emily',
    phone: '+1234567894',
    role: 'staff',
    system_permission: 'member',
    operational_roles: ['support'],
    department: 'Live Support',
    status: 'active',
    join_date: '2024-04-01',
    created_at: '2024-04-01T00:00:00Z',
    updated_at: '2024-04-01T00:00:00Z',
  },
  {
    id: '6',
    email: 'technical1@livestream.com',
    full_name: 'Alex Morgan',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
    role: 'staff',
    system_permission: 'member',
    operational_roles: ['technical'],
    department: 'Live Technical',
    status: 'active',
    join_date: '2024-04-15',
    created_at: '2024-04-15T00:00:00Z',
    updated_at: '2024-04-15T00:00:00Z',
  },
]

// Mock Brands
export const mockBrands: Brand[] = [
  {
    id: 'b1',
    name: 'TechGear Pro',
    logo_url: 'https://api.dicebear.com/7.x/shapes/svg?seed=techgear',
    color: '#2563EB',
    description: 'Consumer electronics and livestream-first product launches.',
    category: 'Electronics',
    status: 'active',
    contact_person: 'Linh Nguyen',
    contact_email: 'brand-contact@techgear.example',
    brand_guideline: 'Use clean product close-ups and demonstrate one benefit at a time.',
    tone_of_voice: 'Clear, confident, practical',
    key_products: ['Wireless Earbuds', 'Smart Watch', 'Charging Accessories'],
    mandatory_claims: ['Official warranty applies to eligible products'],
    restricted_claims: ['Do not claim medical benefits'],
    dos: ['Show product specifications on screen', 'Confirm voucher conditions'],
    donts: ['Do not compare against unnamed competitors'],
    asset_links: ['https://example.com/techgear/brand-assets'],
    updated_by: '1',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'b2',
    name: 'Fashion Nova',
    logo_url: 'https://api.dicebear.com/7.x/shapes/svg?seed=fashion',
    color: '#EC4899',
    description: 'Seasonal fashion collections and social commerce drops.',
    category: 'Fashion',
    status: 'active',
    tone_of_voice: 'Energetic, inclusive, trend-aware',
    key_products: ['Seasonal collections', 'Accessories'],
    updated_by: '1',
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'b3',
    name: 'Beauty Essentials',
    logo_url: 'https://api.dicebear.com/7.x/shapes/svg?seed=beauty',
    color: '#8B5CF6',
    description: 'Beauty essentials, tutorials, and product education.',
    category: 'Beauty',
    status: 'active',
    tone_of_voice: 'Warm, educational, responsible',
    restricted_claims: ['Do not make unverified treatment claims'],
    updated_by: '2',
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2024-02-01T00:00:00Z',
  },
  {
    id: 'b4',
    name: 'Home Living',
    logo_url: 'https://api.dicebear.com/7.x/shapes/svg?seed=home',
    color: '#10B981',
    description: 'Home organization and lifestyle products.',
    category: 'Home & Living',
    status: 'active',
    tone_of_voice: 'Helpful and approachable',
    updated_by: '2',
    created_at: '2024-02-15T00:00:00Z',
    updated_at: '2024-02-15T00:00:00Z',
  },
]

// Mock Platforms
export const mockPlatforms: Platform[] = [
  {
    id: 'p1',
    name: 'TikTok Shop',
    icon: 'tiktok',
    platform_type: 'Social commerce',
    platform_url: 'https://www.tiktok.com/',
    status: 'active',
    account_information: 'Managed business account. Credentials are stored outside this application.',
    policy_notes: 'Follow current commerce and branded-content policies.',
    livestream_rules: ['Disclose promotions clearly', 'Keep products visible during demonstrations'],
    content_restrictions: ['No prohibited products', 'No misleading urgency claims'],
    technical_requirements: ['Stable 10 Mbps upload', 'Vertical 9:16 output'],
    report_requirements: ['Revenue', 'Orders', 'Viewers', 'Product clicks'],
    external_links: ['https://seller.tiktok.com/'],
    updated_by: '1',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p2',
    name: 'Shopee Live',
    icon: 'shopee',
    platform_type: 'Marketplace livestream',
    platform_url: 'https://shopee.com/',
    status: 'active',
    policy_notes: 'Verify voucher stock before announcing offers.',
    livestream_rules: ['Pin the active product', 'Repeat voucher conditions'],
    technical_requirements: ['Stable 8 Mbps upload', 'Mobile-safe audio'],
    report_requirements: ['GMV', 'Orders', 'Viewers'],
    updated_by: '1',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p3',
    name: 'Lazada Live',
    icon: 'lazada',
    platform_type: 'Marketplace livestream',
    platform_url: 'https://www.lazada.com/',
    status: 'active',
    policy_notes: 'Use approved campaign assets.',
    livestream_rules: ['Follow campaign price windows'],
    technical_requirements: ['Stable 8 Mbps upload'],
    report_requirements: ['Revenue', 'Orders', 'Viewers'],
    updated_by: '2',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p4',
    name: 'Facebook Live',
    icon: 'facebook',
    platform_type: 'Social livestream',
    platform_url: 'https://www.facebook.com/live/',
    status: 'active',
    policy_notes: 'Follow branded-content disclosure requirements.',
    livestream_rules: ['Use approved page and scheduled event'],
    technical_requirements: ['Landscape or portrait layout per campaign brief'],
    report_requirements: ['Viewers', 'Engagement', 'Clicks'],
    updated_by: '2',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
]

// Mock Campaigns
export const mockCampaigns: Campaign[] = [
  {
    id: 'c1',
    name: 'Summer Sale 2024',
    brand_id: 'b1',
    start_date: '2024-06-01',
    end_date: '2024-08-31',
    type: 'Seasonal',
    notes: 'Major summer promotion',
    platform_ids: ['p1', 'p2'],
    status: 'completed',
    owner_id: '2',
    campaign_url: 'https://example.com/campaigns/summer-sale',
    created_at: '2024-05-01T00:00:00Z',
    updated_at: '2024-05-01T00:00:00Z',
  },
  {
    id: 'c2',
    name: 'New Collection Launch',
    brand_id: 'b2',
    start_date: '2024-07-01',
    end_date: '2024-07-31',
    type: 'Product Launch',
    notes: 'Fall collection preview',
    platform_ids: ['p2'],
    status: 'completed',
    owner_id: '2',
    campaign_url: 'https://example.com/campaigns/new-collection',
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
  },
  {
    id: 'c3',
    name: 'Flash Sale Week',
    brand_id: 'b3',
    start_date: format(new Date(), 'yyyy-MM-dd'),
    end_date: format(addDays(new Date(), 7), 'yyyy-MM-dd'),
    type: 'Flash Sale',
    notes: 'Daily deals',
    platform_ids: ['p1', 'p3'],
    status: 'active',
    owner_id: '2',
    campaign_url: 'https://example.com/campaigns/flash-sale',
    created_at: '2024-07-01T00:00:00Z',
    updated_at: '2024-07-01T00:00:00Z',
  },
]

// Mock Shifts
const today = new Date()
export const mockShifts: Shift[] = [
  {
    id: 's1',
    date: format(today, 'yyyy-MM-dd'),
    start_time: '09:00',
    end_time: '13:00',
    brand_id: 'b1',
    platform_id: 'p1',
    campaign_id: 'c1',
    title: 'TechGear morning live',
    host_id: '3',
    support_id: '5',
    technical_id: '6',
    required_host_count: 1,
    required_support_count: 1,
    required_technical_count: 1,
    registration_locked: true,
    status: 'scheduled',
    live_link: 'https://tiktok.com/@shop/live',
    product_notes: 'Focus on electronics',
    created_at: format(subDays(today, 5), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    updated_at: format(subDays(today, 5), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
  },
  {
    id: 's2',
    date: format(today, 'yyyy-MM-dd'),
    start_time: '14:00',
    end_time: '18:00',
    brand_id: 'b2',
    platform_id: 'p2',
    campaign_id: 'c2',
    title: 'Fashion launch live',
    host_id: '4',
    support_id: '5',
    technical_id: '6',
    required_host_count: 1,
    required_support_count: 1,
    required_technical_count: 1,
    registration_locked: true,
    status: 'live',
    live_link: 'https://shopee.com/live',
    product_notes: 'New fashion items',
    created_at: format(subDays(today, 3), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    updated_at: format(today, "yyyy-MM-dd'T'HH:mm:ss'Z'"),
  },
  {
    id: 's3',
    date: format(addDays(today, 1), 'yyyy-MM-dd'),
    start_time: '10:00',
    end_time: '14:00',
    brand_id: 'b3',
    platform_id: 'p3',
    campaign_id: 'c3',
    title: 'Beauty flash sale',
    host_id: '3',
    support_id: '5',
    technical_id: '6',
    required_host_count: 1,
    required_support_count: 2,
    required_technical_count: 1,
    registration_locked: false,
    status: 'scheduled',
    live_link: 'https://lazada.com/live',
    product_notes: 'Beauty products demo',
    created_at: format(subDays(today, 2), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    updated_at: format(subDays(today, 2), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
  },
  {
    id: 's4',
    date: format(addDays(today, 2), 'yyyy-MM-dd'),
    start_time: '11:00',
    end_time: '15:00',
    brand_id: 'b4',
    platform_id: 'p4',
    campaign_id: 'c1',
    title: 'Home décor showcase',
    host_id: '4',
    support_id: '5',
    technical_id: '6',
    required_host_count: 2,
    required_support_count: 1,
    required_technical_count: 1,
    registration_locked: false,
    status: 'scheduled',
    live_link: 'https://facebook.com/live',
    product_notes: 'Home decor showcase',
    created_at: format(subDays(today, 1), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    updated_at: format(subDays(today, 1), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
  },
  {
    id: 's5',
    date: format(subDays(today, 1), 'yyyy-MM-dd'),
    start_time: '09:00',
    end_time: '13:00',
    brand_id: 'b1',
    platform_id: 'p1',
    campaign_id: 'c1',
    title: 'Tech gadgets recap',
    host_id: '3',
    support_id: '5',
    technical_id: '6',
    required_host_count: 1,
    required_support_count: 1,
    required_technical_count: 1,
    registration_locked: true,
    status: 'completed',
    live_link: 'https://tiktok.com/@shop/live',
    product_notes: 'Tech gadgets',
    created_at: format(subDays(today, 7), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    updated_at: format(subDays(today, 1), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
  },
  {
    id: 's6',
    date: format(addDays(today, 3), 'yyyy-MM-dd'),
    start_time: '19:00',
    end_time: '22:00',
    brand_id: 'b3',
    platform_id: 'p1',
    campaign_id: 'c3',
    title: 'Beauty evening deal',
    required_host_count: 1,
    required_support_count: 1,
    required_technical_count: 1,
    registration_locked: false,
    allow_multi_role: false,
    status: 'scheduled',
    product_notes: 'Open shift created from the schedule planning workflow.',
    created_at: format(subDays(today, 1), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    updated_at: format(subDays(today, 1), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
  },
]

// Mock Reports
export const mockReports: Report[] = [
  {
    id: 'r1',
    shift_id: 's5',
    revenue: 15420.50,
    orders: 234,
    peak_viewer: 1850,
    average_viewer: 1200,
    likes: 3400,
    comments: 890,
    shares: 120,
    top_products: ['Wireless Earbuds', 'Smart Watch', 'Phone Case', 'Charging Cable', 'Screen Protector'],
    insights_good: 'Great engagement, viewers loved the product demos',
    insights_improvement: 'Need better lighting setup',
    replay_url: 'https://tiktok.com/replay/123',
    dashboard_url: 'https://seller.tiktok.com/dashboard',
    metrics_confirmed: true,
    confirmed_at: format(subDays(today, 1), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    confirmed_by: '1',
    gmv: 15420.5,
    viewers: 1200,
    product_clicks: 980,
    ctr: 4.2,
    cvr: 23.9,
    average_order_value: 65.9,
    live_duration_minutes: 240,
    dashboard_platform: 'tiktok_shop',
    normalized_metrics: {
      revenue: 15420.5,
      gmv: 15420.5,
      orders: 234,
      buyers: 219,
      items_sold: 286,
      total_views: 32800,
      average_view_duration_seconds: 72,
      product_clicks: 980,
      ctr: 4.2,
      conversion_rate: 23.9,
      average_order_value: 65.9,
      likes: 3400,
      comments: 890,
      shares: 120,
      live_duration_seconds: 14400,
    },
    platform_metrics: {
      current_viewers: 1200,
      impressions: 85400,
      gmv_per_hour: 3850000,
      live_ctr: 4.2,
      sku_orders: 234,
      roi_gmv_max: 5.7,
    },
    ocr_review: { status: 'confirmed', metrics: {} },
    status: 'confirmed',
    submitted_by: '3',
    reviewed_by: '2',
    reviewed_at: format(subDays(today, 1), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    created_at: format(subDays(today, 1), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    updated_at: format(subDays(today, 1), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
  },
]

// Mock Dashboard Updates
export const mockDashboardUpdates: DashboardUpdate[] = [
  {
    id: 'du1',
    shift_id: 's2',
    time: format(today, "yyyy-MM-dd'T'14:00:00'Z'"),
    revenue: 2500.00,
    gmv: 2500,
    orders: 45,
    peak_viewers: 850,
    current_viewers: 720,
    total_views: 5600,
    likes: 420,
    comments: 93,
    shares: 18,
    screenshot_url: 'https://placehold.co/800x600/2563EB/white?text=Dashboard+14:00',
    notes: 'Live started strong',
    created_at: format(today, "yyyy-MM-dd'T'14:00:00'Z'"),
    updated_at: format(today, "yyyy-MM-dd'T'14:00:00'Z'"),
  },
  {
    id: 'du2',
    shift_id: 's2',
    time: format(today, "yyyy-MM-dd'T'14:30:00'Z'"),
    revenue: 5200.00,
    gmv: 5200,
    orders: 89,
    peak_viewers: 950,
    current_viewers: 890,
    total_views: 11800,
    likes: 980,
    comments: 214,
    shares: 47,
    screenshot_url: 'https://placehold.co/800x600/2563EB/white?text=Dashboard+14:30',
    notes: 'Peak performance',
    created_at: format(today, "yyyy-MM-dd'T'14:30:00'Z'"),
    updated_at: format(today, "yyyy-MM-dd'T'14:30:00'Z'"),
  },
]

// Mock Swap Requests
export const mockSwapRequests: SwapRequest[] = [
  {
    id: 'sw1',
    shift_id: 's3',
    requester_id: '3',
    operational_role: 'host',
    original_staff_id: '3',
    replacement_staff_id: '4',
    new_host_id: '4',
    reason: 'Family emergency',
    status: 'pending',
    approval_history: [{ action: 'created', by: '3', at: format(today, "yyyy-MM-dd'T'10:00:00'Z'") }],
    created_at: format(today, "yyyy-MM-dd'T'10:00:00'Z'"),
    updated_at: format(today, "yyyy-MM-dd'T'10:00:00'Z'"),
  },
]
