'use client'

import { useState, type ReactNode } from 'react'
import {
  Bell,
  Check,
  ChevronDown,
  FileText,
  KeyRound,
  Link2,
  MoreHorizontal,
  Plus,
  Search,
  Settings2,
  ShieldCheck,
  Users,
} from 'lucide-react'
import { AdminSystemReferenceShell } from './AdminSystemReferenceShell'

type SettingsTab = 'Tổng quan' | 'Cài đặt chung' | 'Quản lý người dùng' | 'Phân quyền' | 'Tích hợp hệ thống' | 'Mẫu & Tài nguyên' | 'Nhật ký hệ thống'

const TABS: SettingsTab[] = ['Tổng quan', 'Cài đặt chung', 'Quản lý người dùng', 'Phân quyền', 'Tích hợp hệ thống', 'Mẫu & Tài nguyên', 'Nhật ký hệ thống']
const USERS = [
  ['Nguyễn Trung Kiên', 'kien.nguyen@ada.ai', 'Admin', 'Đang hoạt động'],
  ['Trần Minh Anh', 'minh.tran@ada.ai', 'Host', 'Đang hoạt động'],
  ['Lê Hoàng', 'hoang.le@ada.ai', 'Camera', 'Đang hoạt động'],
  ['Phạm Anh', 'anh.pham@ada.ai', 'Support', 'Đang hoạt động'],
  ['Dương', 'duong.nguyen@ada.ai', 'Producer', 'Tạm ngưng'],
] as const

export function SettingsReferenceMock() {
  const [tab, setTab] = useState<SettingsTab>('Tổng quan')

  return (
    <AdminSystemReferenceShell active="Settings" searchPlaceholder="Tìm kiếm cài đặt, tích hợp, người dùng...">
      <main className="px-6 py-5">
        <header className="flex items-start justify-between"><div><h1 className="text-[22px] font-bold tracking-tight">Settings</h1><p className="mt-1 text-[12px] text-slate-500">Quản lý cấu hình hệ thống, người dùng, phân quyền và tích hợp</p></div>{tab === 'Cài đặt chung' && <button type="button" className="h-9 rounded-md bg-blue-600 px-4 text-[12px] font-semibold text-white">Lưu thay đổi</button>}</header>
        <div className="mt-4 flex gap-6 border-b border-slate-200">{TABS.map((item) => <button key={item} type="button" onClick={() => setTab(item)} className={`pb-3 text-[11px] font-semibold ${tab === item ? 'border-b-2 border-blue-600 text-blue-600' : 'text-slate-500'}`}>{item}</button>)}</div>
        <div className="mt-4">{tab === 'Tổng quan' && <Overview onNavigate={setTab} />}{tab === 'Cài đặt chung' && <GeneralSettings />}{tab === 'Quản lý người dùng' && <UserManagement />}{tab === 'Phân quyền' && <RolePermissions />}{tab === 'Tích hợp hệ thống' && <Integrations />}{tab === 'Mẫu & Tài nguyên' && <Templates />}{tab === 'Nhật ký hệ thống' && <SystemAudit />}</div>
      </main>
    </AdminSystemReferenceShell>
  )
}

function Overview({ onNavigate }: { onNavigate: (tab: SettingsTab) => void }) {
  return <><div className="grid grid-cols-4 gap-3"><StatCard label="Người dùng" value="24" meta="+2 so với tháng trước" tone="blue" /><StatCard label="Vai trò" value="3" meta="Admin · Leader · Member" tone="violet" /><StatCard label="Tích hợp đang hoạt động" value="4 / 6" meta="TikTok · Shopee · Google Drive · Email" tone="emerald" /><StatCard label="Nhật ký hệ thống" value="128" meta="+12% trong tháng" tone="violet" /></div><div className="mt-4 grid grid-cols-[0.8fr_0.82fr_1.18fr] gap-4"><Section title="Cài đặt nhanh"><QuickLink icon={<Settings2 />} title="Thông tin công ty" copy="Logo, tên công ty, múi giờ, ngôn ngữ" onClick={() => onNavigate('Cài đặt chung')} /><QuickLink icon={<Bell />} title="Thông báo" copy="Email, Push, In-app" onClick={() => onNavigate('Cài đặt chung')} /><QuickLink icon={<Link2 />} title="Tích hợp" copy="TikTok, Shopee, Google Drive, OneDrive" onClick={() => onNavigate('Tích hợp hệ thống')} /><QuickLink icon={<ShieldCheck />} title="Bảo mật" copy="Mật khẩu, phiên đăng nhập, xác thực 2 lớp" onClick={() => onNavigate('Phân quyền')} /><QuickLink icon={<FileText />} title="Hiển thị" copy="Chủ đề, ngôn ngữ, định dạng ngày giờ" onClick={() => onNavigate('Cài đặt chung')} /></Section><Section title="Tích hợp hệ thống"><IntegrationRow name="TikTok Shop" status="Đã kết nối" connected /><IntegrationRow name="Shopee" status="Đã kết nối" connected /><IntegrationRow name="Google Drive" status="Đã kết nối" connected /><IntegrationRow name="Email Service" status="Đã kết nối" connected /><IntegrationRow name="OneDrive" status="Chưa kết nối" /><IntegrationRow name="Slack" status="Tắt" /></Section><Section title="Hoạt động gần đây" action="Xem tất cả" onAction={() => onNavigate('Nhật ký hệ thống')}>{[['Nguyễn Trung Kiên', 'Cập nhật cài đặt thông báo', '2 phút trước'], ['Lê Hoàng', 'Thêm người dùng mới: Phạm Anh', '15 phút trước'], ['Hệ thống', 'Kết nối TikTok Shop thành công', '1 giờ trước'], ['Trần Minh Anh', 'Thay đổi vai trò: Dương → Leader', '3 giờ trước'], ['Hệ thống', 'Đăng nhập từ thiết bị mới', '5 giờ trước']].map(([actor, action, time]) => <div key={`${actor}-${action}`} className="flex gap-3 border-b border-slate-100 py-2 last:border-0"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-blue-50 text-[10px] font-bold text-blue-600">{actor.slice(0, 2).toUpperCase()}</span><div className="min-w-0 flex-1"><strong className="block text-[11px]">{actor}</strong><span className="block truncate text-[10px] text-slate-500">{action}</span></div><span className="text-[10px] text-slate-400">{time}</span></div>)}</Section></div></>
}

function GeneralSettings() {
  const [email, setEmail] = useState(true)
  const [push, setPush] = useState(true)
  const [inApp, setInApp] = useState(true)
  return <div className="grid grid-cols-2 gap-4"><Section title="Thông tin công ty"><Field label="Tên công ty" value="ADA AI" /><div className="grid grid-cols-2 gap-3"><Field label="Múi giờ" value="(UTC+07:00) Bangkok, Hanoi, Jakarta" select /><Field label="Ngôn ngữ" value="Tiếng Việt" select /><Field label="Định dạng ngày" value="DD/MM/YYYY" select /><Field label="Định dạng giờ" value="24 giờ" select /></div><div className="mt-4 flex justify-end gap-2"><button type="button" className="h-9 rounded-md border border-slate-200 px-4 text-[11px] font-semibold">Hủy</button><button type="button" className="h-8 rounded-md bg-blue-600 px-4 text-[11px] font-semibold text-white">Lưu thay đổi</button></div></Section><Section title="Cài đặt thông báo"><h3 className="text-[12px] font-semibold">Kênh thông báo</h3><Toggle label="Thông báo trong ứng dụng" enabled={inApp} onChange={() => setInApp(!inApp)} /><Toggle label="Thông báo email" enabled={email} onChange={() => setEmail(!email)} /><Toggle label="Thông báo đẩy" enabled={push} onChange={() => setPush(!push)} /><h3 className="mt-4 text-[12px] font-semibold">Loại thông báo</h3>{['Lịch làm việc', 'Thay đổi ca', 'Phê duyệt / Từ chối', 'Nhắc nhở quan trọng', 'Báo cáo hàng tuần'].map((item) => <label key={item} className="mt-2 flex items-center gap-2 text-[11px]"><span className="flex h-3.5 w-3.5 items-center justify-center rounded-sm bg-blue-600 text-white"><Check className="h-2.5 w-2.5" /></span>{item}</label>)}</Section></div>
}

function UserManagement() {
  const [drawerOpen, setDrawerOpen] = useState(false)
  return <div className="grid grid-cols-[minmax(0,1fr)_300px] gap-4"><Section title="Quản lý người dùng"><div className="mb-3 flex gap-2"><div className="flex h-9 flex-1 items-center gap-2 rounded-md border border-slate-200 px-3 text-[11px] text-slate-400"><Search className="h-3.5 w-3.5" />Tìm kiếm tên, email, vai trò...</div><button type="button" onClick={() => setDrawerOpen(true)} className="flex h-8 items-center gap-2 rounded-md bg-blue-600 px-4 text-[11px] font-semibold text-white"><Plus className="h-3.5 w-3.5" />Thêm người dùng</button></div><div className="grid grid-cols-[1.2fr_1.4fr_0.7fr_0.8fr_28px] bg-slate-50 px-3 py-2 text-[10px] font-semibold uppercase text-slate-400"><span>Tên</span><span>Email</span><span>Vai trò</span><span>Trạng thái</span><span /></div>{USERS.map(([name, email, role, status]) => <div key={email} className="grid grid-cols-[1.2fr_1.4fr_0.7fr_0.8fr_28px] items-center border-t border-slate-100 px-3 py-2.5 text-[11px]"><strong>{name}</strong><span className="text-slate-500">{email}</span><span>{role}</span><span className={`w-fit rounded px-2 py-1 text-[10px] ${status === 'Đang hoạt động' ? 'bg-emerald-50 text-emerald-600' : 'bg-slate-100 text-slate-500'}`}>{status}</span><MoreHorizontal className="h-3.5 w-3.5 text-slate-400" /></div>)}</Section><aside className="rounded-lg border border-slate-200 bg-white p-4"><h2 className="text-[13px] font-bold">{drawerOpen ? 'Thêm người dùng mới' : 'Tóm tắt người dùng'}</h2>{drawerOpen ? <div className="mt-3"><Field label="Họ và tên" value="Lê Thu Hà" /><Field label="Email" value="lethuha@ada.com" /><div className="grid grid-cols-2 gap-2"><Field label="Vai trò" value="Host" select /><Field label="Brand mặc định" value="Pharmaton" select /></div><Field label="Ghi chú" value="Thêm ghi chú..." /><div className="mt-4 flex gap-2"><button type="button" onClick={() => setDrawerOpen(false)} className="h-9 flex-1 rounded-md border border-slate-200 text-[11px] font-semibold">Hủy</button><button type="button" className="h-8 flex-1 rounded-md bg-blue-600 text-[11px] font-semibold text-white">Tạo người dùng</button></div></div> : <div className="mt-3 space-y-2"><SummaryLine label="Tổng người dùng" value="24" /><SummaryLine label="Đang hoạt động" value="22" /><SummaryLine label="Tạm ngưng" value="2" /><SummaryLine label="Admin" value="3" /><SummaryLine label="Leader" value="4" /><SummaryLine label="Member" value="17" /></div>}</aside></div>
}

function RolePermissions() {
  const [role, setRole] = useState('Leader')
  const roles = ['Admin', 'Leader', 'Member']
  const leaderPermissions = ['Xem lịch làm việc', 'Phê duyệt đổi ca', 'Quản lý nhân sự', 'Xem báo cáo', 'Xuất dữ liệu']
  return <div className="grid grid-cols-[260px_1fr] gap-4"><Section title="Vai trò hệ thống">{roles.map((item) => <button key={item} type="button" onClick={() => setRole(item)} className={`mb-2 flex w-full items-center gap-3 rounded-md border p-3 text-left ${role === item ? 'border-blue-500 bg-blue-50' : 'border-slate-100'}`}><span className="flex h-8 w-8 items-center justify-center rounded-full bg-violet-50 text-violet-600"><KeyRound className="h-4 w-4" /></span><span className="flex-1"><strong className="block text-[12px]">{item}</strong><small className="text-[10px] text-slate-400">{item === 'Admin' ? 'Toàn quyền hệ thống' : 'Quyền vận hành được giới hạn'}</small></span></button>)}</Section><Section title={`Quyền hạn · ${role}`}><div className="grid grid-cols-2 gap-3">{['Xem lịch làm việc', 'Đăng ký ca', 'Đổi ca (Request)', 'Phê duyệt đổi ca', 'Quản lý nhân sự', 'Xem báo cáo', 'Quản trị hệ thống', 'Xuất dữ liệu'].map((permission, index) => { const enabled = role === 'Admin' || (role === 'Leader' ? leaderPermissions.includes(permission) : index < 3); return <label key={permission} className="flex items-center gap-2 rounded-md border border-slate-100 p-3 text-[11px]"><span className={`flex h-4 w-4 items-center justify-center rounded-sm border ${enabled ? 'border-blue-600 bg-blue-600 text-white' : 'border-slate-300'}`}>{enabled && <Check className="h-3 w-3" />}</span>{permission}</label> })}</div><div className="mt-4 flex justify-end gap-2"><button type="button" className="h-9 rounded-md border border-slate-200 px-4 text-[11px] font-semibold">Hủy</button><button type="button" className="h-8 rounded-md bg-blue-600 px-4 text-[11px] font-semibold text-white">Lưu thay đổi</button></div></Section></div>
}

function Integrations() { return <div className="grid grid-cols-2 gap-4"><Section title="Tích hợp thương mại & nội dung"><IntegrationCard name="TikTok Shop" copy="Đồng bộ sản phẩm và phiên livestream" connected /><IntegrationCard name="Shopee" copy="Đồng bộ đơn hàng và chiến dịch" connected /><IntegrationCard name="Slack" copy="Nhận thông báo vận hành theo thời gian thực" /></Section><Section title="Lưu trữ & dữ liệu"><IntegrationCard name="Google Drive" copy="Lưu trữ file, tài liệu và bản sao dữ liệu" connected /><IntegrationCard name="OneDrive" copy="Lưu trữ tài liệu doanh nghiệp" /><IntegrationCard name="Email Service" copy="Gửi thông báo và báo cáo định kỳ" connected /></Section></div> }
function Templates() { return <Section title="Mẫu & Tài nguyên"><div className="grid grid-cols-3 gap-3">{[['Mẫu nhập nhân sự', 'XLSX · Cập nhật 19/09/2026'], ['Mẫu nhập ca làm việc', 'XLSX · Cập nhật 21/09/2026'], ['Hướng dẫn quản trị hệ thống', 'PDF · Phiên bản 1.4'], ['Quy trình phân quyền', 'PDF · Phiên bản 2.0'], ['Mẫu báo cáo livestream', 'XLSX · Cập nhật 23/09/2026'], ['Bộ nhận diện thương hiệu', 'ZIP · 18.4 MB']].map(([name, meta]) => <button key={name} type="button" className="flex items-center gap-3 rounded-md border border-slate-100 p-3 text-left"><span className="flex h-9 w-9 items-center justify-center rounded-md bg-blue-50 text-blue-600"><FileText className="h-4 w-4" /></span><span className="flex-1"><strong className="block text-[12px]">{name}</strong><small className="text-[10px] text-slate-400">{meta}</small></span><span className="text-[11px] font-semibold text-blue-600">Tải</span></button>)}</div></Section> }
function SystemAudit() { return <Section title="Nhật ký hệ thống" action="Xuất file"><div className="mb-3 flex gap-2"><FieldButton label="Tất cả hành động" /><FieldButton label="01/09/2026 – 30/09/2026" wide /><FieldButton label="Tất cả người dùng" /></div><div className="grid grid-cols-[96px_1fr_1.2fr_1fr_90px] bg-slate-50 px-3 py-2 text-[10px] font-semibold uppercase text-slate-400"><span>Thời gian</span><span>Người dùng</span><span>Hành động</span><span>Đối tượng</span><span>IP</span></div>{[['10/09 14:32', 'Nguyễn Trung Kiên', 'Tạo thương hiệu', 'Opella', '192.168.1.10'], ['10/09 13:20', 'Lê Hoàng', 'Cập nhật người dùng', 'Minh Anh', '192.168.1.12'], ['10/09 11:05', 'Mai', 'Nhập dữ liệu', 'Products', '192.168.1.15'], ['09/09 16:42', 'Khánh', 'Phê duyệt chiến dịch', '9.9 Campaign', '192.168.1.11'], ['09/09 14:18', 'Linh', 'Cập nhật cài đặt', 'Notification', '192.168.1.10']].map((row) => <div key={row.join('-')} className="grid grid-cols-[96px_1fr_1.2fr_1fr_90px] border-t border-slate-100 px-3 py-2.5 text-[11px]">{row.map((cell) => <span key={cell}>{cell}</span>)}</div>)}</Section> }

function Section({ title, action, onAction, children }: { title: string; action?: string; onAction?: () => void; children: ReactNode }) { return <section className="rounded-lg border border-slate-200 bg-white p-4"><header className="mb-3 flex items-center justify-between border-b border-slate-100 pb-3"><h2 className="text-[13px] font-bold">{title}</h2>{action && <button type="button" onClick={onAction} className="text-[11px] font-semibold text-blue-600">{action} →</button>}</header>{children}</section> }
function StatCard({ label, value, meta, tone }: { label: string; value: string; meta: string; tone: 'blue' | 'violet' | 'emerald' }) { const colors = tone === 'blue' ? 'bg-blue-50 text-blue-600' : tone === 'emerald' ? 'bg-emerald-50 text-emerald-600' : 'bg-violet-50 text-violet-600'; return <div className="rounded-lg border border-slate-200 bg-white p-4"><div className="flex items-center gap-3"><span className={`flex h-9 w-9 items-center justify-center rounded-full ${colors}`}><Users className="h-4 w-4" /></span><div><span className="text-[11px] text-slate-500">{label}</span><strong className="block text-[18px]">{value}</strong></div></div><div className="mt-2 text-[10px] text-emerald-600">↑ {meta}</div></div> }
function QuickLink({ icon, title, copy, onClick }: { icon: ReactNode; title: string; copy: string; onClick: () => void }) { return <button type="button" onClick={onClick} className="flex w-full items-center gap-3 border-b border-slate-100 py-2 text-left last:border-0"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-blue-50 text-blue-600 [&>svg]:h-3.5 [&>svg]:w-3.5">{icon}</span><span className="flex-1"><strong className="block text-[11px]">{title}</strong><small className="text-[10px] text-slate-400">{copy}</small></span><span className="text-slate-300">›</span></button> }
function IntegrationRow({ name, status, connected = false }: { name: string; status: string; connected?: boolean }) { return <div className="flex items-center gap-3 border-b border-slate-100 py-2 last:border-0"><span className="flex h-7 w-7 items-center justify-center rounded-md bg-slate-900 text-[10px] font-bold text-white">{name.slice(0, 2)}</span><span className="flex-1 text-[11px] font-medium">{name}</span><span className={`rounded px-2 py-1 text-[10px] ${connected ? 'bg-emerald-50 text-emerald-600' : 'bg-amber-50 text-amber-600'}`}>{status}</span></div> }
function IntegrationCard({ name, copy, connected = false }: { name: string; copy: string; connected?: boolean }) { return <div className="mb-2 flex items-center gap-3 rounded-md border border-slate-100 p-3"><span className="flex h-9 w-9 items-center justify-center rounded-md bg-slate-900 text-[11px] font-bold text-white">{name.slice(0, 2)}</span><div className="flex-1"><strong className="block text-[12px]">{name}</strong><span className="text-[10px] text-slate-400">{copy}</span></div><span className={`rounded px-2 py-1 text-[10px] ${connected ? 'bg-emerald-50 text-emerald-600' : 'bg-amber-50 text-amber-600'}`}>{connected ? 'Đã kết nối' : 'Chưa kết nối'}</span><button type="button" className="h-7 rounded border border-blue-200 px-2 text-[10px] font-semibold text-blue-600">{connected ? 'Cấu hình' : 'Kết nối'}</button></div> }
function Field({ label, value, select = false }: { label: string; value: string; select?: boolean }) { return <label className="mb-3 block text-[11px] font-semibold text-slate-600">{label}<span className="mt-1 flex h-9 items-center justify-between rounded-md border border-slate-200 px-3 font-normal">{value}{select && <ChevronDown className="h-3.5 w-3.5" />}</span></label> }
function Toggle({ label, enabled, onChange }: { label: string; enabled: boolean; onChange: () => void }) { return <button type="button" onClick={onChange} className="mt-2 flex w-full items-center justify-between text-[11px]"><span>{label}</span><span className={`flex h-4 w-8 items-center rounded-full p-0.5 ${enabled ? 'justify-end bg-blue-600' : 'justify-start bg-slate-200'}`}><span className="h-3 w-3 rounded-full bg-white" /></span></button> }
function SummaryLine({ label, value }: { label: string; value: string }) { return <div className="flex justify-between border-b border-slate-100 pb-2 text-[11px]"><span className="text-slate-400">{label}</span><strong>{value}</strong></div> }
function FieldButton({ label, wide = false }: { label: string; wide?: boolean }) { return <button type="button" className={`flex h-8 items-center justify-between rounded-md border border-slate-200 px-3 text-[11px] ${wide ? 'w-[220px]' : 'w-[160px]'}`}>{label}<ChevronDown className="h-3 w-3" /></button> }
