// tests/harness/coreV1Roles.ts
// Reusable 3-role harness - TEST INFRASTRUCTURE ONLY. No business logic mutation.
// Defines canonical role contracts derived from production lib/permissions.

import type { SystemPermission, User } from '@/lib/types/database.types'
import { permissionMatrix } from '@/lib/permissions'

export type CoreRole = SystemPermission // 'admin' | 'leader' | 'member'

export const CORE_ROLES: readonly CoreRole[] = ['admin', 'leader', 'member'] as const

// --- Canonical permission sets (frozen copy of production at time of harness creation) ---
// These are expected values; tests assert production matrix equals these.
// If production matrix intentionally changes, update harness in same PR with explicit justification.
// Do not edit this file to make failing tests pass without product review.
export const CANONICAL_MEMBER_PERMISSIONS = new Set([
  'shifts.view_assigned',
  'shifts.view_open',
  'shifts.register',
  'shifts.cancel_registration',
  'reports.submit',
  'swaps.request',
  'profile.edit_own',
  'settings.member',
] as const)

export const CANONICAL_LEADER_EXTRA = new Set([
  'shifts.approve_registration',
  'shifts.assign_staff',
  'shifts.edit',
  'shifts.lock',
  'shifts.import',
  'shifts.export',
  'reports.review',
  'reports.export',
  'swaps.approve',
  'swaps.export',
  'settings.leader',
  'campaigns.edit_operational',
  'audit.view_team',
] as const)

export const CANONICAL_ADMIN_EXTRA = new Set([
  'staff.manage',
  'brands.manage',
  'platforms.manage',
  'campaigns.manage',
  'settings.admin',
  'permissions.manage',
  'audit.view',
  'audit.restore',
  'audit.review',
  'data.force_delete',
  'shifts.delete',
] as const)

export const CANONICAL_COUNTS: Record<CoreRole, number> = {
  member: CANONICAL_MEMBER_PERMISSIONS.size,
  leader: CANONICAL_MEMBER_PERMISSIONS.size + CANONICAL_LEADER_EXTRA.size,
  admin: CANONICAL_MEMBER_PERMISSIONS.size + CANONICAL_LEADER_EXTRA.size + CANONICAL_ADMIN_EXTRA.size,
}

// Runtime expectation derived from canonical sets (for deterministic comparison)
export function canonicalSetFor(role: CoreRole): ReadonlySet<string> {
  if (role === 'member') return CANONICAL_MEMBER_PERMISSIONS as unknown as ReadonlySet<string>
  if (role === 'leader') return new Set([...CANONICAL_MEMBER_PERMISSIONS as unknown as string[], ...CANONICAL_LEADER_EXTRA as unknown as string[]])
  return new Set([...CANONICAL_MEMBER_PERMISSIONS as unknown as string[], ...CANONICAL_LEADER_EXTRA as unknown as string[], ...CANONICAL_ADMIN_EXTRA as unknown as string[]])
}

export function productionSetFor(role: CoreRole): ReadonlySet<string> {
  return permissionMatrix[role] as unknown as ReadonlySet<string>
}

// --- Mock User factory (no secrets, no DB) ---
export function makeMockUser(overrides: Partial<User> & { role?: CoreRole; system_permission?: CoreRole } = {}): User {
  const perm = (overrides.system_permission ?? overrides.role ?? 'member') as CoreRole
  const legacyRole = perm === 'admin' ? 'admin' : perm === 'leader' ? 'leader' : 'staff'
  return {
    id: overrides.id ?? `user-${perm}-1`,
    email: overrides.email ?? `${perm}@example.test`,
    display_name: overrides.display_name ?? `${perm} user`,
    role: legacyRole as User['role'],
    system_permission: perm,
    operational_roles: overrides.operational_roles ?? (['host'] as User['operational_roles']),
    status: overrides.status ?? 'active',
    archived_at: overrides.archived_at ?? null,
    deleted_at: overrides.deleted_at ?? null,
    avatar_url: null,
    phone: null,
    department: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  } as unknown as User
}

export function makeInactiveUser(role: CoreRole, extra: Partial<User> = {}): User {
  return makeMockUser({ ...extra, system_permission: role, status: 'inactive' as User['status'] })
}
export function makeArchivedUser(role: CoreRole, extra: Partial<User> = {}): User {
  return makeMockUser({ ...extra, system_permission: role, archived_at: new Date().toISOString() })
}
export function makeDeletedUser(role: CoreRole, extra: Partial<User> = {}): User {
  return makeMockUser({ ...extra, system_permission: role, deleted_at: new Date().toISOString() })
}

// Helper for deterministic PASS/FAIL reporting
export interface HarnessCheck {
  label: string
  role: CoreRole | 'unauthenticated' | 'all'
  area: string
  passed: boolean
  details?: string
}

export function formatChecks(checks: readonly HarnessCheck[]): string {
  const pass = checks.filter(c => c.passed).length
  const fail = checks.length - pass
  const lines = checks.map(c => `${c.passed ? 'PASS' : 'FAIL'} [${c.role}] ${c.area} :: ${c.label}${c.details ? ` — ${c.details}` : ''}`)
  return [`Core V1 3-role harness: ${pass} PASS / ${fail} FAIL / ${checks.length} total`, ...lines].join('\n')
}
